// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NhaMeoShop.Models;

namespace NhaMeoShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("NhaMeoShop.Models.ChiTietHoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("DGBan")
                        .HasColumnType("float");

                    b.Property<string>("GhiChuHoaDon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoaDonSoHD")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaSP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SLBan")
                        .HasColumnType("int");

                    b.Property<string>("SanPhamMaSP")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SoHD")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HoaDonSoHD");

                    b.HasIndex("SanPhamMaSP");

                    b.ToTable("ChiTietHoaDons");
                });

            modelBuilder.Entity("NhaMeoShop.Models.ChiTietPhieuNhap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("DGNhap")
                        .HasColumnType("float");

                    b.Property<string>("GhiChuNhap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KhoTongMaNL")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaNL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhieuNhapSoPN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SLNhap")
                        .HasColumnType("int");

                    b.Property<string>("SoPN")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KhoTongMaNL");

                    b.HasIndex("PhieuNhapSoPN");

                    b.ToTable("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("NhaMeoShop.Models.ChiTietPhieuXuat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GhiChuXuat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KhoPhaCheMaKhoPC")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaKhoPC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhieuXuatSoPX")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SLXuat")
                        .HasColumnType("int");

                    b.Property<string>("SoPX")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KhoPhaCheMaKhoPC");

                    b.HasIndex("PhieuXuatSoPX");

                    b.ToTable("ChiTietPhieuXuats");
                });

            modelBuilder.Entity("NhaMeoShop.Models.HoaDon", b =>
                {
                    b.Property<string>("SoHD")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GhiChuHD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HinhThuc")
                        .HasColumnType("bit");

                    b.Property<bool>("HinhThucTT")
                        .HasColumnType("bit");

                    b.Property<string>("KhachHangMaKH")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("KhuyenMai")
                        .HasColumnType("float");

                    b.Property<string>("MaKH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanVienMaNV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("PhuPhi")
                        .HasColumnType("float");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("SoHD");

                    b.HasIndex("KhachHangMaKH");

                    b.HasIndex("NhanVienMaNV");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("NhaMeoShop.Models.KhachHang", b =>
                {
                    b.Property<string>("MaKH")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChuKH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiKHMaLoaiKH")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaLoaiKH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayDKTV")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySinhKH")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDTKH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKH");

                    b.HasIndex("LoaiKHMaLoaiKH");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("NhaMeoShop.Models.KhoPhaChe", b =>
                {
                    b.Property<string>("MaKhoPC")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GhiChuKhoPC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SLTonQuy")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaKhoPC");

                    b.ToTable("KhoPhaChe");
                });

            modelBuilder.Entity("NhaMeoShop.Models.KhoTong", b =>
                {
                    b.Property<string>("MaNL")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("DonGiaNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DonViNhapNL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DonViSuDungNL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChuNL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TiLeQuyDoi")
                        .HasColumnType("real");

                    b.HasKey("MaNL");

                    b.ToTable("KhoTong");
                });

            modelBuilder.Entity("NhaMeoShop.Models.LoaiKH", b =>
                {
                    b.Property<string>("MaLoaiKH")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GhiChuLoaiKH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("GiamGia")
                        .HasColumnType("float");

                    b.Property<string>("TenLoaiKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLoaiKH");

                    b.ToTable("LoaiKHs");
                });

            modelBuilder.Entity("NhaMeoShop.Models.LoaiNCC", b =>
                {
                    b.Property<string>("MaLoaiNCC")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoaiNCC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLoaiNCC");

                    b.ToTable("LoaiNCCs");
                });

            modelBuilder.Entity("NhaMeoShop.Models.LoaiNhanVien", b =>
                {
                    b.Property<string>("MaLoaiNV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GhiChuLoaiNV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("HeSoLuongNV")
                        .HasColumnType("float");

                    b.Property<string>("TenLoaiNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLoaiNV");

                    b.ToTable("LoaiNhanViens");
                });

            modelBuilder.Entity("NhaMeoShop.Models.LoaiSanPham", b =>
                {
                    b.Property<string>("MaLoaiSP")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GhiChuLoaiSP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoaiSP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLoaiSP");

                    b.ToTable("LoaiSanPhams");
                });

            modelBuilder.Entity("NhaMeoShop.Models.NCC", b =>
                {
                    b.Property<string>("MaNCC")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChiNCC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChuNCC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiNCCMaLoaiNCC")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaLoaiNCC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoTKNCC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNCC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTKNCC")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNCC");

                    b.HasIndex("LoaiNCCMaLoaiNCC");

                    b.ToTable("NCCs");
                });

            modelBuilder.Entity("NhaMeoShop.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CCCD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChiNV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChuNV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiNhanVienMaLoaiNV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaLoaiNV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinhNV")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PhaiNV")
                        .HasColumnType("bit");

                    b.Property<string>("SoDTNV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TKNganHangNV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNganHangNV")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNV");

                    b.HasIndex("LoaiNhanVienMaLoaiNV");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("NhaMeoShop.Models.PhieuNhap", b =>
                {
                    b.Property<string>("SoPN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GhiChuPN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GiaoHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNCC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NCCMaNCC")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanVienMaNV")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SoPN");

                    b.HasIndex("NCCMaNCC");

                    b.HasIndex("NhanVienMaNV");

                    b.ToTable("PhieuNhaps");
                });

            modelBuilder.Entity("NhaMeoShop.Models.PhieuXuat", b =>
                {
                    b.Property<string>("SoPX")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GhiChuPX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayXuat")
                        .HasColumnType("datetime2");

                    b.Property<string>("XuatHang")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SoPX");

                    b.ToTable("PhieuXuats");
                });

            modelBuilder.Entity("NhaMeoShop.Models.SanPham", b =>
                {
                    b.Property<string>("MaSP")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("DonGiaSP")
                        .HasColumnType("float");

                    b.Property<string>("GhiChuSP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnhSP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaLoaiSP")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSP");

                    b.HasIndex("MaLoaiSP");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NhaMeoShop.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("NhaMeoShop.Models.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("HoaDonSoHD");

                    b.HasOne("NhaMeoShop.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("SanPhamMaSP");

                    b.Navigation("HoaDon");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("NhaMeoShop.Models.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("NhaMeoShop.Models.KhoTong", "KhoTong")
                        .WithMany()
                        .HasForeignKey("KhoTongMaNL");

                    b.HasOne("NhaMeoShop.Models.PhieuNhap", "PhieuNhap")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("PhieuNhapSoPN");

                    b.Navigation("KhoTong");

                    b.Navigation("PhieuNhap");
                });

            modelBuilder.Entity("NhaMeoShop.Models.ChiTietPhieuXuat", b =>
                {
                    b.HasOne("NhaMeoShop.Models.KhoPhaChe", "KhoPhaChe")
                        .WithMany()
                        .HasForeignKey("KhoPhaCheMaKhoPC");

                    b.HasOne("NhaMeoShop.Models.PhieuXuat", "PhieuXuat")
                        .WithMany("ChiTietPhieuXuats")
                        .HasForeignKey("PhieuXuatSoPX");

                    b.Navigation("KhoPhaChe");

                    b.Navigation("PhieuXuat");
                });

            modelBuilder.Entity("NhaMeoShop.Models.HoaDon", b =>
                {
                    b.HasOne("NhaMeoShop.Models.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("KhachHangMaKH");

                    b.HasOne("NhaMeoShop.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienMaNV");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("NhaMeoShop.Models.KhachHang", b =>
                {
                    b.HasOne("NhaMeoShop.Models.LoaiKH", "LoaiKH")
                        .WithMany("KhachHangs")
                        .HasForeignKey("LoaiKHMaLoaiKH");

                    b.Navigation("LoaiKH");
                });

            modelBuilder.Entity("NhaMeoShop.Models.NCC", b =>
                {
                    b.HasOne("NhaMeoShop.Models.LoaiNCC", "LoaiNCC")
                        .WithMany("NCCs")
                        .HasForeignKey("LoaiNCCMaLoaiNCC");

                    b.Navigation("LoaiNCC");
                });

            modelBuilder.Entity("NhaMeoShop.Models.NhanVien", b =>
                {
                    b.HasOne("NhaMeoShop.Models.LoaiNhanVien", "LoaiNhanVien")
                        .WithMany("NhanViens")
                        .HasForeignKey("LoaiNhanVienMaLoaiNV");

                    b.Navigation("LoaiNhanVien");
                });

            modelBuilder.Entity("NhaMeoShop.Models.PhieuNhap", b =>
                {
                    b.HasOne("NhaMeoShop.Models.NCC", "NCC")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("NCCMaNCC");

                    b.HasOne("NhaMeoShop.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienMaNV");

                    b.Navigation("NCC");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("NhaMeoShop.Models.SanPham", b =>
                {
                    b.HasOne("NhaMeoShop.Models.LoaiSanPham", "LoaiSanPham")
                        .WithMany()
                        .HasForeignKey("MaLoaiSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiSanPham");
                });

            modelBuilder.Entity("NhaMeoShop.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("NhaMeoShop.Models.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("NhaMeoShop.Models.LoaiKH", b =>
                {
                    b.Navigation("KhachHangs");
                });

            modelBuilder.Entity("NhaMeoShop.Models.LoaiNCC", b =>
                {
                    b.Navigation("NCCs");
                });

            modelBuilder.Entity("NhaMeoShop.Models.LoaiNhanVien", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("NhaMeoShop.Models.NCC", b =>
                {
                    b.Navigation("PhieuNhaps");
                });

            modelBuilder.Entity("NhaMeoShop.Models.PhieuNhap", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("NhaMeoShop.Models.PhieuXuat", b =>
                {
                    b.Navigation("ChiTietPhieuXuats");
                });
#pragma warning restore 612, 618
        }
    }
}
